name: CI
on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  Build:
    name: Prepare(Build,UnitTest)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
          
      - name: Get short SHA
        id: s_sha
        run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8
          
      #build
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        id: build_gradle
        run: ./gradlew build -x test -x check

      - name: Notify slack build success
        if: ${{ always() && steps.build_gradle.outcome == 'success' }}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          # Updates existing message from the first step
          message_id: ${{ steps.slack_build.outputs.message_id }}
          channel: github_action
          status: BUILD SUCCESS commit:${{ steps.s_sha.outputs.sha8 }}
          color: good

      - name: Notify slack build failed
        if: ${{ always() && steps.build_gradle.outcome == 'failure' }}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          # Updates existing message from the first step
          message_id: ${{ steps.slack_build.outputs.message_id }}
          channel: github_action
          status: BUILD FAILED commit:${{ steps.s_sha.outputs.sha8 }}
          color: danger
